### ISSUE TITLE
Where is the table of contents?

### ISSUE THREAD

**Issue by jbalogh** [mozilla-services/metlog-py#10]
The homepage (http://readthedocs.org/docs/metlog-py/en/latest/) links to:
- http://readthedocs.org/docs/metlog-py/en/latest/api/client.html
- http://readthedocs.org/docs/metlog-py/en/latest/api/senders.html
- http://readthedocs.org/docs/metlog-py/en/latest/config.html

which seem like they could be top-level pages, but they're buried within paragraphs of other text on the homepage.

**Comment by rafrombrc** [comment]
Sphinx doesn't seem to make it as easy as I'd like to replace the page-specific ToC w/ a docs-wide ToC on just the home page. I've added a "contents" section after the intro text, hopefully this will suffice.

http://readthedocs.org/docs/metlog-py/en/latest/index.html#contents

**Comment by jbalogh** [comment]
Thanks! I remember tables of contents being pretty easy using the `:toctree` and `:glob` when I used to write docs. Did something change?

**Comment by rafrombrc** [comment]
No, generating the table of contents is easy enough. What's weird to me is that there's a prominent ToC in the sidebar which is an auto-generated ToC for that page. I'd like to see that replaced by the docs-wide ToC, but only on the home page. Or maybe have it pushed down so that the docs-wide ToC _and_ the page overview section is on each page. The latter wouldn't be hard, just some template customization, I'll probably end up doing that.
