### ISSUE TITLE
Improve StdoutSender output

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/metlog-py#13]
Pretty print when possible the output of the StdoutSender.

For instance I guess we could print out \n chars in the payload

**Comment by rafrombrc** [comment]
Okay, I've made 2 changes here. First, the StdOutSender now defaults to just emitting the payload and not the full JSON. Second, when you _do_ decide to emit the full JSON, it's using the `indent` argument to json.dumps to make for prettier output. Does this make it nicer?

**Comment by tarekziade** [comment]
the prettyfication is awesome !

o/wise: I am been thinking about this again and I think json is not the best syntax for stdout.

what about turning it into logging-like lines ? values separated but ":" or something like that ?

**Comment by rafrombrc** [comment]
Rather than hard-coding another output format, I made the output format on the StreamSender (upon which the StdOutSender is based) configurable. It defaults to the prettified JSON as before, but now you can pass in an alternate formatter as either a callable or a dotted name to generate whatever output you want.

Note that since this is defined as a sender argument and since it accepts dotted names, that means that you can already manage this using config files, like so:

```
[metlog]
sender_class = metlog.senders.dev.StdOutSender
sender_formatter = dotted.path.to.your.formatter.function
```

I'm considering this closed for now, please reopen if you have any problems or think this isn't sufficient.
