### ISSUE TITLE
client.exception should add exception info

### ISSUE THREAD

**Issue by rfk** [mozilla-services/metlog-py#26]
The stdlib Logger.exception method adds traceback info about the currently-active exception.  In the interests of API compatibility maybe Client.exception could do the same?

**Comment by rafrombrc** [comment]
Yeah, this makes sense. And we might as well add support for the `exc_info` keyword arg to the all of them. Then we'd match the call signature of the logging module's methods in every way except for the `extra` argument. We should probably support that one, too, but it's a bit less straightforward what to _do_ with it since it's basically a logging.LogRecord class specific detail.

**Comment by rafrombrc** [comment]
c024cf7dbf57c1bc21b65358a98e24949f9c0eb9
